// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAE1ADKwGX-PVjqJr3ZdnXk-B3jQYxuYA',
    appId: '1:168661777099:web:ef6b070de60801ef60b94e',
    messagingSenderId: '168661777099',
    projectId: 'automaticscoring-8ec10',
    authDomain: 'automaticscoring-8ec10.firebaseapp.com',
    storageBucket: 'automaticscoring-8ec10.appspot.com',
    measurementId: 'G-4KELR4JTFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEpHMPjXANzfc-yAOWdttGBaLIvEY1aE',
    appId: '1:168661777099:android:1584f40b72c524c560b94e',
    messagingSenderId: '168661777099',
    projectId: 'automaticscoring-8ec10',
    storageBucket: 'automaticscoring-8ec10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoROmNiV5xr7Q4Gnpco5MKF4uGda1sG0Q',
    appId: '1:168661777099:ios:7ee2b9aec6eb2b3a60b94e',
    messagingSenderId: '168661777099',
    projectId: 'automaticscoring-8ec10',
    storageBucket: 'automaticscoring-8ec10.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoROmNiV5xr7Q4Gnpco5MKF4uGda1sG0Q',
    appId: '1:168661777099:ios:b2eb9771dfe3b19a60b94e',
    messagingSenderId: '168661777099',
    projectId: 'automaticscoring-8ec10',
    storageBucket: 'automaticscoring-8ec10.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
